//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarPartsAccounting.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AutopartsShopEntities : DbContext
    {
        public AutopartsShopEntities()
            : base("name=AutopartsShopEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<accounting> accounting { get; set; }
        public virtual DbSet<clients> clients { get; set; }
        public virtual DbSet<parts> parts { get; set; }
        public virtual DbSet<sales> sales { get; set; }
        public virtual DbSet<sold_parts> sold_parts { get; set; }
    }
}
