//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarPartsAccounting.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class sold_parts
    {
        public Nullable<int> selling_id { get; set; }
        public Nullable<int> part_id { get; set; }
        public int id { get; set; }
    
        public virtual accounting accounting { get; set; }
        public virtual parts parts { get; set; }
    }
}
